import type { MenuDataModel } from "../menu/menuItem.model";

export const menuData: MenuDataModel = {
	mainHeaderText: "Manufacturing",
	subHeaderText: "System Menu",
	menuItems: [
		{
			id: "partners",
			text: "Partners",
			icon: "user-friends",
			iconColor: "text-indigo-400",
			isFolder: false,
			items: [],
			params: {
				screenType: "table",
				table: {
					name: "timer_fpr2",
					columns: [
						{
							name: "codef",
							label: "Code",
							type: "string",
							primaryKey: true,
							retrieve: true,
							retrieveCriteria: true,
							insert: true,
							update: false,
							visible: true,
							sortable: true,
							filterable: true,
							editable: false,
						},
						{
							name: "epon",
							label: "Surname",
							type: "string",
							retrieve: true,
							retrieveCriteria: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "onom",
							label: "Name",
							type: "string",
							retrieve: true,
							retrieveCriteria: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "pat",
							label: "Father Name",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "active_from",
							label: "Active From",
							type: "datetime",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "active_to",
							label: "Active To",
							type: "datetime",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "sex",
							label: "Sex",
							type: "number",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "birthday",
							label: "Birthday",
							type: "datetime",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "address",
							label: "Address",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "tel",
							label: "Phone",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "email",
							label: "Email",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "mht",
							label: "Mother Name",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "tel2",
							label: "Phone 2",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "adt",
							label: "ID Number",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "afm",
							label: "AFM",
							type: "string",
							retrieve: true,
							retrieveCriteria: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "amka",
							label: "AMKA",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "ama",
							label: "AMA",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
						{
							name: "internal_tel",
							label: "Internal Tel",
							type: "string",
							retrieve: true,
							insert: true,
							update: true,
							visible: true,
							sortable: true,
							filterable: true,
							editable: true,
						},
					],
				},
			},
		},
	],
};
